config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales', to: 'sales#done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco) }
  validates :value, numericality: { only_integer: true, greater_than: 0 }
validates :discount, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sales = Sale.new
  end

  def create
    @sales = Sale.new(sale_params)
   puts @sales.category
   if @sales.tax == 1
     @sales.total = @sales.value - (@sales.value * @sales.discount / 100)
   else
     @sales.total = (@sales.value - (@sales.value * @sales.discount / 100)) * 1.19
   end
   puts @sales.total
   @sales.save
   redirect_to sales_path
  end

  def done
   @sales = Sale.all
  end

  private

  def sale_params
   params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presencial25</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<div class="container">
  <h1>se almaceno el registro</h1>
  <div class="table-responsive">
    <table class="table">
      <tr>
        <th>codigo</th>
        <th>detalle</th>
        <th>categoria</th>
        <th>valor</th>
        <th>descuento</th>
        <th>total</th>
      </tr>
        <%@sales.each do |sale|%>
      <tr>
        <td><%= sale.cod%></td>
        <td><%= sale.detail%></td>
        <td><%= sale.category%></td>
        <td><%= sale.value%></td>
        <td><%= sale.discount%></td>
        <td><%= sale.total%></td>
      </tr>  <%end%>
    </table>
  </div>
  <%= link_to 'volver', sales_new_path%>
</div>

app/views/sales/new.html.erb
<div class="container">

<h1>VENTAS EN RAILS</h1>
<br>
<%= form_with model: Sale, class:"form-horizontal", class:"form-horizontal", local: true do |f|%>
<div class="form-group">
  <%=f.label "Codigo", class: "col-md-2"%>
  <%=f.number_field :cod%>
</div>
<div class="form-group">
  <%=f.label "detalle", class: "col-md-2"%>
  <%=f.text_area :detail%>
</div>
<div class="form-group">
  <%=f.label "categoria", class: "col-md-2"%>
  <%=f.text_field :category%>
  </div>
<div class="form-group">
  <%=f.label "valor", class: "col-md-2"%>
  <%=f.number_field :value%>
</div>
<div class="form-group">
  <%=f.label "descuento", class: "col-md-2"%>
  <%=f.number_field :discount%>
</div>
<div class="form-group">
  <%=f.label "Exento de IVA", class: "col-md-2"%>
  <%=f.check_box :tax%>
</div>
<%=f.submit "Enviar"%>
<% end %>

</div>